import { Download, Eye, Plus, Printer, Trash2 } from 'lucide-react';
import { useMemo, useState, type FormEvent } from 'react';
import { Modal } from '../components/Modal';
import { PageHeader } from '../components/PageHeader';
import { SearchBar } from '../components/SearchBar';
import { TransactionItemsEditor } from '../components/TransactionItemsEditor';
import { billBalance, billTotal, currency, documentNo, downloadCsv, inventoryRows, itemsSubtotal, itemsTax, today, uid } from '../lib/helpers';
import { useApp } from '../store/AppContext';
import type { Bill, BillType } from '../types';

export function Bills(){
  const {data,addBill,deleteBill}=useApp(); const first=data.materials[0];
  const empty=(type:BillType='Purchase'):Bill=>({id:uid('bill'),billNo:documentNo(type==='Purchase'?'PB':'CB',data.bills.filter(b=>b.type===type).length),type,date:today(),dueDate:today(),supplierId:type==='Purchase'?data.suppliers[0]?.id:undefined,siteId:type==='Client'?data.sites[0]?.id:undefined,partyName:type==='Purchase'?data.suppliers[0]?.name??'':data.sites[0]?.clientName??'',referenceNo:'',items:[{id:uid('bi'),materialId:first?.id??'',quantity:1,rate:first?.standardRate??0,taxRate:first?.taxRate??0}],discount:0,otherCharges:0,notes:'',status:'Unpaid',inventoryPosting:'Auto Post',createdAt:new Date().toISOString()});
  const[query,setQuery]=useState('');const[filter,setFilter]=useState<'All'|BillType>('All');const[open,setOpen]=useState(false);const[view,setView]=useState<Bill|null>(null);const[draft,setDraft]=useState<Bill>(empty());
  const filtered=useMemo(()=>data.bills.filter(b=>(filter==='All'||b.type===filter)&&`${b.billNo} ${b.partyName} ${b.referenceNo} ${b.status}`.toLowerCase().includes(query.toLowerCase())),[data.bills,filter,query]);
  const submit=(e:FormEvent)=>{e.preventDefault();if(draft.inventoryPosting==='Auto Post'&&draft.type==='Client'){const stock=inventoryRows(data);const shortage=draft.items.find(item=>item.quantity>(stock.find(row=>row.id===item.materialId)?.availableQty??0));if(shortage&&data.settings.strictStockControl){const material=data.materials.find(item=>item.id===shortage.materialId);alert(`Insufficient stock for ${material?.name??'material'}. Available: ${stock.find(row=>row.id===shortage.materialId)?.availableQty??0}`);return;}}addBill(draft);setOpen(false);};
  const changeType=(type:BillType)=>setDraft({...draft,type,billNo:documentNo(type==='Purchase'?'PB':'CB',data.bills.filter(b=>b.type===type).length),supplierId:type==='Purchase'?data.suppliers[0]?.id:undefined,siteId:type==='Client'?data.sites[0]?.id:undefined,partyName:type==='Purchase'?data.suppliers[0]?.name??'':data.sites[0]?.clientName??''});
  const printBill=(bill:Bill)=>{setView(bill);setTimeout(()=>window.print(),100)};
  return <div className="page-stack"><PageHeader eyebrow="Accounts receivable & payable" title="Bills & invoices" description="Create supplier purchase bills and client/site invoices with tax, discounts, due dates and payment status." actions={<><button className="button secondary" onClick={()=>downloadCsv('bills.csv',filtered.map(b=>({Bill:b.billNo,Type:b.type,Date:b.date,DueDate:b.dueDate,Party:b.partyName,Reference:b.referenceNo,Total:billTotal(b),Balance:billBalance(data,b),Status:b.status})))}><Download size={17}/> Export</button><button className="button primary" onClick={()=>{setDraft(empty('Purchase'));setOpen(true);}}><Plus size={17}/> New bill</button></>} />
  <section className="panel table-panel"><div className="table-toolbar split-toolbar"><SearchBar value={query} onChange={setQuery} placeholder="Search bill, party, reference or status..."/><div className="segmented">{(['All','Purchase','Client'] as const).map(v=><button key={v} className={filter===v?'active':''} onClick={()=>setFilter(v)}>{v}</button>)}</div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Bill</th><th>Type / date</th><th>Party</th><th>Reference</th><th>Total</th><th>Paid</th><th>Balance</th><th>Stock posting</th><th>Status</th><th/></tr></thead><tbody>{filtered.map(b=>{const balance=billBalance(data,b);const total=billTotal(b);return <tr key={b.id}><td><strong>{b.billNo}</strong><span>Due {new Date(b.dueDate).toLocaleDateString('en-IN')}</span></td><td><span className={`soft-badge ${b.type==='Purchase'?'warning-badge':''}`}>{b.type}</span><span>{new Date(b.date).toLocaleDateString('en-IN')}</span></td><td><strong>{b.partyName}</strong><span>{b.type==='Purchase'?'Supplier payable':'Client receivable'}</span></td><td>{b.referenceNo||'—'}</td><td><strong>{currency(total)}</strong></td><td>{currency(total-balance)}</td><td><strong className={balance>0?'negative-text':'positive-text'}>{currency(balance)}</strong></td><td><span className={`soft-badge ${b.inventoryPosting==='Auto Post'?'':'warning-badge'}`}>{b.inventoryPosting}</span></td><td><span className={`status-pill status-${b.status.toLowerCase().replaceAll(' ','-')}`}>{b.status}</span></td><td><div className="row-actions"><button className="icon-button" onClick={()=>setView(b)}><Eye size={16}/></button><button className="icon-button" onClick={()=>printBill(b)}><Printer size={16}/></button><button className="icon-button danger" onClick={()=>confirm(`Delete ${b.billNo}?`)&&deleteBill(b.id)}><Trash2 size={16}/></button></div></td></tr>})}</tbody></table></div></section>
  <Modal open={open} title="Create bill" subtitle="Choose purchase for supplier bills or client for project billing." onClose={()=>setOpen(false)} wide><form className="form-stack" onSubmit={submit}><div className="segmented form-segmented"><button type="button" className={draft.type==='Purchase'?'active':''} onClick={()=>changeType('Purchase')}>Purchase bill</button><button type="button" className={draft.type==='Client'?'active':''} onClick={()=>changeType('Client')}>Client invoice</button></div><div className="form-grid three"><label><span>Bill number *</span><input required value={draft.billNo} onChange={e=>setDraft({...draft,billNo:e.target.value})}/></label><label><span>Bill date *</span><input required type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label><span>Due date *</span><input required type="date" value={draft.dueDate} onChange={e=>setDraft({...draft,dueDate:e.target.value})}/></label>
  {draft.type==='Purchase'?<label className="span-2"><span>Supplier *</span><select required value={draft.supplierId??''} onChange={e=>{const s=data.suppliers.find(x=>x.id===e.target.value);setDraft({...draft,supplierId:e.target.value,partyName:s?.name??''})}}><option value="">Select supplier</option>{data.suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>:<label className="span-2"><span>Project / client *</span><select required value={draft.siteId??''} onChange={e=>{const s=data.sites.find(x=>x.id===e.target.value);setDraft({...draft,siteId:e.target.value,partyName:s?.clientName||s?.name||''})}}><option value="">Select project</option>{data.sites.map(s=><option key={s.id} value={s.id}>{s.name} — {s.clientName}</option>)}</select></label>}
  <label><span>Reference number</span><input value={draft.referenceNo} onChange={e=>setDraft({...draft,referenceNo:e.target.value})} placeholder="Invoice / PO / RA bill"/></label></div><TransactionItemsEditor materials={data.materials} items={draft.items} onChange={items=>setDraft({...draft,items})}/><div className="form-grid three"><label><span>Discount</span><input type="number" min="0" step="0.01" value={draft.discount} onChange={e=>setDraft({...draft,discount:Number(e.target.value)})}/></label><label><span>Other charges</span><input type="number" min="0" step="0.01" value={draft.otherCharges} onChange={e=>setDraft({...draft,otherCharges:Number(e.target.value)})}/></label><label><span>Stock posting</span><select value={draft.inventoryPosting} onChange={e=>setDraft({...draft,inventoryPosting:e.target.value as Bill['inventoryPosting']})}><option>Auto Post</option><option>Accounting Only</option></select><small>{draft.type==='Purchase'?'Auto Post adds invoice quantities to central stock.':'Auto Post deducts invoice quantities from central stock.'}</small></label></div><div className="inline-notice"><strong>Integrated posting</strong><span>Saving this invoice creates the accounting voucher automatically. With Auto Post, the inventory ledger is updated at the same time.</span></div><div className="document-total"><span>Subtotal {currency(itemsSubtotal(draft.items))}</span><span>Tax {currency(itemsTax(draft.items))}</span><span>Charges {currency(draft.otherCharges)}</span><span>Discount -{currency(draft.discount)}</span><strong>Grand total {currency(billTotal(draft))}</strong></div><label><span>Notes / terms</span><textarea rows={3} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><div className="form-actions"><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button primary">Save bill</button></div></form></Modal>
  <Modal open={Boolean(view)} title={view?.billNo??'Bill'} subtitle="Print-ready invoice view" onClose={()=>setView(null)} wide>{view&&<div className="invoice-print"><div className="invoice-brand"><div><h2>{data.settings.companyName}</h2><p>{data.settings.address}<br/>{data.settings.gstin&&`GSTIN: ${data.settings.gstin}`}</p></div><div className="invoice-type"><strong>{view.type==='Purchase'?'PURCHASE BILL':'TAX INVOICE'}</strong><span>{view.billNo}</span></div></div><div className="invoice-meta"><div><span>Party</span><strong>{view.partyName}</strong></div><div><span>Bill date</span><strong>{new Date(view.date).toLocaleDateString('en-IN')}</strong></div><div><span>Due date</span><strong>{new Date(view.dueDate).toLocaleDateString('en-IN')}</strong></div><div><span>Reference</span><strong>{view.referenceNo||'—'}</strong></div></div><table className="items-table"><thead><tr><th>#</th><th>Material</th><th>Qty</th><th>Rate</th><th>Tax</th><th>Amount</th></tr></thead><tbody>{view.items.map((i,index)=><tr key={i.id}><td>{index+1}</td><td>{data.materials.find(m=>m.id===i.materialId)?.name}</td><td>{i.quantity} {data.materials.find(m=>m.id===i.materialId)?.unit}</td><td>{currency(i.rate)}</td><td>{i.taxRate}%</td><td>{currency(i.quantity*i.rate*(1+i.taxRate/100))}</td></tr>)}</tbody></table><div className="invoice-summary"><div><span>Notes</span><p>{view.notes||'Thank you for your business.'}</p></div><div className="invoice-totals"><p><span>Subtotal</span><strong>{currency(itemsSubtotal(view.items))}</strong></p><p><span>Tax</span><strong>{currency(itemsTax(view.items))}</strong></p><p><span>Other charges</span><strong>{currency(view.otherCharges)}</strong></p><p><span>Discount</span><strong>-{currency(view.discount)}</strong></p><p className="grand"><span>Grand total</span><strong>{currency(billTotal(view))}</strong></p></div></div><div className="form-actions no-print"><button className="button primary" onClick={()=>window.print()}><Printer size={17}/> Print bill</button></div></div>}</Modal>
  </div>;
}
