import { Download, Plus, Trash2, WalletCards } from 'lucide-react';
import { useMemo, useState, type FormEvent } from 'react';
import { Modal } from '../components/Modal';
import { PageHeader } from '../components/PageHeader';
import { SearchBar } from '../components/SearchBar';
import { billBalance, currency, documentNo, downloadCsv, today, uid } from '../lib/helpers';
import { useApp } from '../store/AppContext';
import type { Payment } from '../types';

export function Payments(){
  const {data,addPayment,deletePayment}=useApp();const openBills=data.bills.filter(b=>billBalance(data,b)>0);const firstBill=openBills[0];
  const empty=():Payment=>({id:uid('pay'),paymentNo:documentNo('PAY',data.payments.length),date:today(),billId:firstBill?.id??'',partyName:firstBill?.partyName??'',direction:firstBill?.type==='Client'?'Received':'Paid',amount:firstBill?billBalance(data,firstBill):0,mode:'Bank Transfer',reference:'',notes:'',createdAt:new Date().toISOString()});
  const[query,setQuery]=useState('');const[open,setOpen]=useState(false);const[draft,setDraft]=useState<Payment>(empty());const[error,setError]=useState('');
  const filtered=useMemo(()=>data.payments.filter(p=>`${p.paymentNo} ${p.partyName} ${p.reference} ${p.mode}`.toLowerCase().includes(query.toLowerCase())),[data.payments,query]);
  const submit=(e:FormEvent)=>{e.preventDefault();const bill=data.bills.find(b=>b.id===draft.billId);if(!bill)return;const balance=billBalance(data,bill);if(draft.amount<=0||draft.amount>balance){setError(`Payment must be more than zero and cannot exceed ${currency(balance)}.`);return;}addPayment(draft);setOpen(false);setError('');};
  const selectBill=(id:string)=>{const bill=data.bills.find(b=>b.id===id);setDraft({...draft,billId:id,partyName:bill?.partyName??'',direction:bill?.type==='Client'?'Received':'Paid',amount:bill?billBalance(data,bill):0});};
  return <div className="page-stack"><PageHeader eyebrow="Cash flow" title="Payments" description="Record supplier payments and client receipts against bills with bank, UPI, cheque, card or cash references." actions={<><button className="button secondary" onClick={()=>downloadCsv('payments.csv',filtered.map(p=>({Payment:p.paymentNo,Date:p.date,Party:p.partyName,Direction:p.direction,Amount:p.amount,Mode:p.mode,Reference:p.reference})))}><Download size={17}/> Export</button><button className="button primary" disabled={!openBills.length} onClick={()=>{setDraft(empty());setOpen(true);}}><Plus size={17}/> Record payment</button></>} />
  <section className="stats-grid mini-stats"><article className="stat-card"><div className="stat-icon"><WalletCards size={21}/></div><div className="stat-copy"><span>Total paid</span><strong>{currency(data.payments.filter(p=>p.direction==='Paid').reduce((s,p)=>s+p.amount,0))}</strong><small>Supplier outflow</small></div></article><article className="stat-card"><div className="stat-icon"><WalletCards size={21}/></div><div className="stat-copy"><span>Total received</span><strong>{currency(data.payments.filter(p=>p.direction==='Received').reduce((s,p)=>s+p.amount,0))}</strong><small>Client collections</small></div></article><article className="stat-card"><div className="stat-icon"><WalletCards size={21}/></div><div className="stat-copy"><span>Open bills</span><strong>{openBills.length}</strong><small>Awaiting settlement</small></div></article></section>
  <section className="panel table-panel"><div className="table-toolbar"><SearchBar value={query} onChange={setQuery} placeholder="Search payment, party, mode or reference..."/><div className="toolbar-summary"><strong>{filtered.length}</strong><span>payments</span></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Payment</th><th>Date</th><th>Party</th><th>Against bill</th><th>Direction</th><th>Mode</th><th>Reference</th><th>Amount</th><th/></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><strong>{p.paymentNo}</strong><span>{p.notes||'Payment entry'}</span></td><td>{new Date(p.date).toLocaleDateString('en-IN')}</td><td><strong>{p.partyName}</strong></td><td>{data.bills.find(b=>b.id===p.billId)?.billNo||'—'}</td><td><span className={`status-pill ${p.direction==='Received'?'success':'warning'}`}>{p.direction}</span></td><td>{p.mode}</td><td>{p.reference||'—'}</td><td><strong className={p.direction==='Received'?'positive-text':''}>{currency(p.amount)}</strong></td><td><button className="icon-button danger" onClick={()=>confirm(`Delete ${p.paymentNo}? Bill status will be recalculated on the next payment entry.`)&&deletePayment(p.id)}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div></section>
  <Modal open={open} title="Record payment" subtitle="Payments are allocated to a specific open bill." onClose={()=>setOpen(false)}><form className="form-stack" onSubmit={submit}>{error&&<div className="alert danger-alert">{error}</div>}<div className="form-grid two"><label><span>Payment number *</span><input required value={draft.paymentNo} onChange={e=>setDraft({...draft,paymentNo:e.target.value})}/></label><label><span>Date *</span><input required type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label className="span-2"><span>Open bill *</span><select required value={draft.billId} onChange={e=>selectBill(e.target.value)}><option value="">Select bill</option>{openBills.map(b=><option key={b.id} value={b.id}>{b.billNo} — {b.partyName} — Balance {currency(billBalance(data,b))}</option>)}</select></label><label><span>Direction</span><select value={draft.direction} onChange={e=>setDraft({...draft,direction:e.target.value as Payment['direction']})}><option>Paid</option><option>Received</option></select></label><label><span>Amount *</span><input required type="number" min="0.01" step="0.01" value={draft.amount} onChange={e=>setDraft({...draft,amount:Number(e.target.value)})}/></label><label><span>Mode</span><select value={draft.mode} onChange={e=>setDraft({...draft,mode:e.target.value as Payment['mode']})}><option>Cash</option><option>Bank Transfer</option><option>Cheque</option><option>UPI</option><option>Card</option></select></label><label><span>Reference</span><input value={draft.reference} onChange={e=>setDraft({...draft,reference:e.target.value})} placeholder="UTR / cheque / transaction ID"/></label><label className="span-2"><span>Notes</span><textarea rows={3} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label></div><div className="form-actions"><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button primary">Save payment</button></div></form></Modal>
  </div>;
}
