import { Download, Eye, Plus, Trash2 } from 'lucide-react';
import { useMemo, useState, type FormEvent } from 'react';
import { Modal } from '../components/Modal';
import { PageHeader } from '../components/PageHeader';
import { SearchBar } from '../components/SearchBar';
import { TransactionItemsEditor } from '../components/TransactionItemsEditor';
import { currency, documentNo, downloadCsv, itemsSubtotal, itemsTax, today, uid } from '../lib/helpers';
import { useApp } from '../store/AppContext';
import type { Receipt, TransactionItem } from '../types';

const makeItems = (materialId = '', rate = 0, taxRate = 0): TransactionItem[] => [{ id: uid('ri'), materialId, quantity: 1, rate, taxRate }];

export function Receipts() {
  const { data, addReceipt, deleteReceipt } = useApp();
  const firstMaterial = data.materials[0];
  const empty = (): Receipt => ({ id: uid('rec'), receiptNo: documentNo('GRN', data.receipts.length), date: today(), supplierId: data.suppliers[0]?.id ?? '', invoiceNo: '', vehicleNo: '', receivedBy: '', destination: 'Central Store', siteId: undefined, items: makeItems(firstMaterial?.id, firstMaterial?.standardRate, firstMaterial?.taxRate), notes: '', createdAt: new Date().toISOString() });
  const [query, setQuery] = useState(''); const [open, setOpen] = useState(false); const [view, setView] = useState<Receipt | null>(null); const [draft, setDraft] = useState<Receipt>(empty());
  const filtered = useMemo(() => data.receipts.filter((r) => `${r.receiptNo} ${r.invoiceNo} ${r.vehicleNo} ${data.suppliers.find(s=>s.id===r.supplierId)?.name}`.toLowerCase().includes(query.toLowerCase())), [data.receipts,data.suppliers,query]);
  const total=(r:Receipt)=>itemsSubtotal(r.items)+itemsTax(r.items);
  const submit=(e:FormEvent)=>{e.preventDefault(); if(!draft.supplierId || !draft.items.length) return; addReceipt(draft);setOpen(false);};
  return <div className="page-stack">
    <PageHeader eyebrow="Goods inward" title="Material received" description="Record supplier deliveries, GRNs, invoice references, vehicles and direct-to-site receipts." actions={<><button className="button secondary" onClick={()=>downloadCsv('material-receipts.csv',filtered.map(r=>({GRN:r.receiptNo,Date:r.date,Supplier:data.suppliers.find(s=>s.id===r.supplierId)?.name,Invoice:r.invoiceNo,Vehicle:r.vehicleNo,Destination:r.destination,Value:total(r)})))}><Download size={17}/> Export</button><button className="button primary" onClick={()=>{setDraft(empty());setOpen(true);}}><Plus size={17}/> Receive material</button></>} />
    <section className="panel table-panel"><div className="table-toolbar"><SearchBar value={query} onChange={setQuery} placeholder="Search GRN, supplier, invoice or vehicle..."/><div className="toolbar-summary"><strong>{filtered.length}</strong><span>receipts</span></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>GRN</th><th>Date</th><th>Supplier</th><th>Invoice / vehicle</th><th>Destination</th><th>Items</th><th>Total value</th><th/></tr></thead><tbody>{filtered.map((r)=><tr key={r.id}><td><strong>{r.receiptNo}</strong><span>Received by {r.receivedBy||'—'}</span></td><td>{new Date(r.date).toLocaleDateString('en-IN')}</td><td>{data.suppliers.find(s=>s.id===r.supplierId)?.name||'—'}</td><td><strong>{r.invoiceNo||'No invoice'}</strong><span>{r.vehicleNo||'No vehicle'}</span></td><td><span className="soft-badge">{r.destination}</span>{r.siteId&&<span>{data.sites.find(s=>s.id===r.siteId)?.name}</span>}</td><td>{r.items.length}</td><td><strong>{currency(total(r))}</strong></td><td><div className="row-actions"><button className="icon-button" onClick={()=>setView(r)}><Eye size={16}/></button><button className="icon-button danger" onClick={()=>confirm(`Delete ${r.receiptNo}? Stock will be recalculated.`)&&deleteReceipt(r.id)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div></section>
    <Modal open={open} title="Receive material" subtitle="Create a goods receipt note. Stock increases immediately after saving." onClose={()=>setOpen(false)} wide><form className="form-stack" onSubmit={submit}><div className="form-grid three">
      <label><span>GRN number *</span><input required value={draft.receiptNo} onChange={e=>setDraft({...draft,receiptNo:e.target.value})}/></label><label><span>Receipt date *</span><input required type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label><span>Supplier *</span><select required value={draft.supplierId} onChange={e=>setDraft({...draft,supplierId:e.target.value})}><option value="">Select supplier</option>{data.suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
      <label><span>Supplier invoice no.</span><input value={draft.invoiceNo} onChange={e=>setDraft({...draft,invoiceNo:e.target.value})}/></label><label><span>Vehicle no.</span><input value={draft.vehicleNo} onChange={e=>setDraft({...draft,vehicleNo:e.target.value.toUpperCase()})}/></label><label><span>Received by</span><input value={draft.receivedBy} onChange={e=>setDraft({...draft,receivedBy:e.target.value})}/></label>
      <label><span>Destination</span><select value={draft.destination} onChange={e=>setDraft({...draft,destination:e.target.value as Receipt['destination'],siteId:e.target.value==='Central Store'?undefined:draft.siteId})}><option>Central Store</option><option>Direct to Site</option></select></label>{draft.destination==='Direct to Site'&&<label className="span-2"><span>Site *</span><select required value={draft.siteId??''} onChange={e=>setDraft({...draft,siteId:e.target.value})}><option value="">Select site</option>{data.sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}
    </div><TransactionItemsEditor materials={data.materials} items={draft.items} onChange={items=>setDraft({...draft,items})}/><div className="document-total"><span>Subtotal {currency(itemsSubtotal(draft.items))}</span><span>Tax {currency(itemsTax(draft.items))}</span><strong>Total {currency(itemsSubtotal(draft.items)+itemsTax(draft.items))}</strong></div><label><span>Notes</span><textarea rows={3} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><div className="form-actions"><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button primary">Save GRN & update stock</button></div></form></Modal>
    <Modal open={Boolean(view)} title={view?.receiptNo??'Receipt'} subtitle="Goods receipt details" onClose={()=>setView(null)} wide>{view&&<div className="document-view"><div className="document-meta"><div><span>Supplier</span><strong>{data.suppliers.find(s=>s.id===view.supplierId)?.name}</strong></div><div><span>Date</span><strong>{new Date(view.date).toLocaleDateString('en-IN')}</strong></div><div><span>Invoice</span><strong>{view.invoiceNo||'—'}</strong></div><div><span>Vehicle</span><strong>{view.vehicleNo||'—'}</strong></div></div><table className="items-table"><thead><tr><th>Material</th><th>Qty</th><th>Rate</th><th>Tax</th><th>Total</th></tr></thead><tbody>{view.items.map(i=><tr key={i.id}><td>{data.materials.find(m=>m.id===i.materialId)?.name}</td><td>{i.quantity} {data.materials.find(m=>m.id===i.materialId)?.unit}</td><td>{currency(i.rate)}</td><td>{i.taxRate}%</td><td>{currency(i.quantity*i.rate*(1+i.taxRate/100))}</td></tr>)}</tbody></table><div className="document-total"><strong>Total {currency(total(view))}</strong></div></div>}</Modal>
  </div>;
}
