import { Download, FileSpreadsheet, Landmark, PackageSearch, ReceiptIndianRupee } from 'lucide-react';
import { useMemo, useState } from 'react';
import { PageHeader } from '../components/PageHeader';
import { billBalance, billTotal, currency, downloadCsv, inventoryRows, number } from '../lib/helpers';
import { useApp } from '../store/AppContext';

export function Reports(){
  const {data}=useApp();const[tab,setTab]=useState<'Inventory'|'Supplier Ledger'|'Site Consumption'|'Tax Summary'>('Inventory');const stock=inventoryRows(data);
  const supplierRows=useMemo(()=>data.suppliers.map(s=>{const bills=data.bills.filter(b=>b.supplierId===s.id);const billed=bills.reduce((sum,b)=>sum+billTotal(b),0);const paid=data.payments.filter(p=>bills.some(b=>b.id===p.billId)).reduce((sum,p)=>sum+p.amount,0);return{supplier:s.name,opening:s.openingBalance,billed,paid,balance:s.openingBalance+billed-paid};}),[data]);
  const siteRows=useMemo(()=>data.sites.map(site=>{const issues=data.supplies.filter(s=>s.siteId===site.id);const direct=data.receipts.filter(r=>r.destination==='Direct to Site'&&r.siteId===site.id);const quantity=issues.reduce((sum,s)=>sum+s.items.reduce((a,i)=>a+i.quantity,0),0)+direct.reduce((sum,r)=>sum+r.items.reduce((a,i)=>a+i.quantity,0),0);const value=issues.reduce((sum,s)=>sum+s.items.reduce((a,i)=>a+i.quantity*i.rate,0),0)+direct.reduce((sum,r)=>sum+r.items.reduce((a,i)=>a+i.quantity*i.rate,0),0);const invoices=data.bills.filter(b=>b.siteId===site.id).reduce((sum,b)=>sum+billTotal(b),0);return{site:site.name,client:site.clientName,issues:issues.length+direct.length,quantity,value,invoices,budget:site.budget};}),[data]);
  const taxRows=useMemo(()=>{const map=new Map<number,{taxable:number,tax:number}>();data.bills.forEach(b=>b.items.forEach(i=>{const current=map.get(i.taxRate)??{taxable:0,tax:0};current.taxable+=i.quantity*i.rate;current.tax+=i.quantity*i.rate*i.taxRate/100;map.set(i.taxRate,current);}));return [...map].map(([rate,v])=>({rate,...v,total:v.taxable+v.tax}));},[data]);
  const exportCurrent=()=>{if(tab==='Inventory')downloadCsv('inventory-report.csv',stock.map(s=>({Code:s.code,Material:s.name,Category:s.category,Opening:s.openingStock,GRNReceived:s.receivedQty,InvoicePurchased:s.purchasedQty,SiteIssued:s.suppliedQty,InvoiceSold:s.soldQty,Available:s.availableQty,Unit:s.unit,Rate:s.standardRate,Value:s.stockValue})));if(tab==='Supplier Ledger')downloadCsv('supplier-ledger.csv',supplierRows);if(tab==='Site Consumption')downloadCsv('site-consumption.csv',siteRows);if(tab==='Tax Summary')downloadCsv('tax-summary.csv',taxRows);};
  return <div className="page-stack"><PageHeader eyebrow="Management information" title="Reports & ledgers" description="Operational and financial reports for stock, suppliers, projects and tax." actions={<button className="button primary" onClick={exportCurrent}><Download size={17}/> Export current report</button>} />
  <div className="report-tabs">{([{name:'Inventory',icon:PackageSearch},{name:'Supplier Ledger',icon:Landmark},{name:'Site Consumption',icon:FileSpreadsheet},{name:'Tax Summary',icon:ReceiptIndianRupee}] as const).map(({name,icon:Icon})=><button className={tab===name?'active':''} onClick={()=>setTab(name)} key={name}><Icon size={18}/><span>{name}</span></button>)}</div>
  <section className="panel report-panel"><div className="panel-header"><div><span className="eyebrow">Generated from live data</span><h2>{tab}</h2></div><span className="soft-badge">As of {new Date().toLocaleDateString('en-IN')}</span></div>
  {tab==='Inventory'&&<div className="table-scroll"><table className="data-table"><thead><tr><th>Material</th><th>Opening</th><th>GRN inward</th><th>Invoice inward</th><th>Site issue</th><th>Invoice outward</th><th>Available</th><th>Rate</th><th>Value</th></tr></thead><tbody>{stock.map(s=><tr key={s.id}><td><strong>{s.name}</strong><span>{s.code} · {s.category}</span></td><td>{number(s.openingStock)} {s.unit}</td><td className="positive-text">{number(s.receivedQty)} {s.unit}</td><td className="positive-text">{number(s.purchasedQty)} {s.unit}</td><td className="negative-text">{number(s.suppliedQty)} {s.unit}</td><td className="negative-text">{number(s.soldQty)} {s.unit}</td><td><strong>{number(s.availableQty)} {s.unit}</strong></td><td>{currency(s.standardRate)}</td><td><strong>{currency(s.stockValue)}</strong></td></tr>)}</tbody><tfoot><tr><td colSpan={8}>Total inventory value</td><td>{currency(stock.reduce((sum,s)=>sum+s.stockValue,0))}</td></tr></tfoot></table></div>}
  {tab==='Supplier Ledger'&&<div className="table-scroll"><table className="data-table"><thead><tr><th>Supplier</th><th>Opening balance</th><th>Purchase billed</th><th>Payments</th><th>Closing payable</th></tr></thead><tbody>{supplierRows.map(r=><tr key={r.supplier}><td><strong>{r.supplier}</strong></td><td>{currency(r.opening)}</td><td>{currency(r.billed)}</td><td className="positive-text">{currency(r.paid)}</td><td><strong className={r.balance>0?'negative-text':''}>{currency(r.balance)}</strong></td></tr>)}</tbody><tfoot><tr><td>Total</td><td>{currency(supplierRows.reduce((s,r)=>s+r.opening,0))}</td><td>{currency(supplierRows.reduce((s,r)=>s+r.billed,0))}</td><td>{currency(supplierRows.reduce((s,r)=>s+r.paid,0))}</td><td>{currency(supplierRows.reduce((s,r)=>s+r.balance,0))}</td></tr></tfoot></table></div>}
  {tab==='Site Consumption'&&<div className="table-scroll"><table className="data-table"><thead><tr><th>Site / client</th><th>Issue notes</th><th>Total quantity*</th><th>Material value</th><th>Client invoices</th><th>Budget utilization</th></tr></thead><tbody>{siteRows.map(r=><tr key={r.site}><td><strong>{r.site}</strong><span>{r.client}</span></td><td>{r.issues}</td><td>{number(r.quantity)}</td><td><strong>{currency(r.value)}</strong></td><td>{currency(r.invoices)}</td><td><div className="utilization"><span>{r.budget?Math.min(100,r.value/r.budget*100).toFixed(1):0}%</span><div className="progress-track"><i style={{width:`${r.budget?Math.min(100,r.value/r.budget*100):0}%`}}/></div></div></td></tr>)}</tbody></table><p className="report-note">*Quantity combines different units and is useful only as an activity indicator. Material value is the comparable measure.</p></div>}
  {tab==='Tax Summary'&&<div className="table-scroll"><table className="data-table"><thead><tr><th>Tax rate</th><th>Taxable value</th><th>Tax amount</th><th>Gross total</th></tr></thead><tbody>{taxRows.map(r=><tr key={r.rate}><td><strong>{r.rate}%</strong></td><td>{currency(r.taxable)}</td><td>{currency(r.tax)}</td><td><strong>{currency(r.total)}</strong></td></tr>)}</tbody><tfoot><tr><td>Total</td><td>{currency(taxRows.reduce((s,r)=>s+r.taxable,0))}</td><td>{currency(taxRows.reduce((s,r)=>s+r.tax,0))}</td><td>{currency(taxRows.reduce((s,r)=>s+r.total,0))}</td></tr></tfoot></table></div>}
  </section><section className="stats-grid mini-stats"><article className="stat-card"><div className="stat-copy"><span>Total billed</span><strong>{currency(data.bills.reduce((s,b)=>s+billTotal(b),0))}</strong><small>Purchase and client bills</small></div></article><article className="stat-card"><div className="stat-copy"><span>Open balance</span><strong>{currency(data.bills.reduce((s,b)=>s+billBalance(data,b),0))}</strong><small>Across all unsettled bills</small></div></article><article className="stat-card"><div className="stat-copy"><span>Transactions</span><strong>{data.receipts.length+data.supplies.length+data.bills.length+data.payments.length}</strong><small>Recorded operational documents</small></div></article></section>
  </div>;
}
