import { Database, RotateCcw, Save, ShieldCheck } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { PageHeader } from '../components/PageHeader';
import { isSupabaseConfigured } from '../lib/supabase';
import { useApp } from '../store/AppContext';

export function Settings(){
  const {data,setData,resetDemo}=useApp();const[draft,setDraft]=useState(data.settings);const[saved,setSaved]=useState(false);
  const submit=(e:FormEvent)=>{e.preventDefault();setData(current=>({...current,settings:draft}));setSaved(true);setTimeout(()=>setSaved(false),1800);};
  return <div className="page-stack"><PageHeader eyebrow="Configuration" title="Company & system settings" description="Control invoice identity, tax defaults, database mode and demo data." />
  <section className="settings-grid"><article className="panel"><div className="panel-header"><div><span className="eyebrow">Business profile</span><h2>Company information</h2></div></div><form className="form-stack" onSubmit={submit}><div className="form-grid two"><label className="span-2"><span>Company name *</span><input required value={draft.companyName} onChange={e=>setDraft({...draft,companyName:e.target.value})}/></label><label><span>GSTIN</span><input value={draft.gstin} onChange={e=>setDraft({...draft,gstin:e.target.value.toUpperCase()})}/></label><label><span>Phone</span><input value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label><label><span>Email</span><input type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label><span>Currency</span><select value={draft.currency} onChange={e=>setDraft({...draft,currency:e.target.value})}><option value="INR">INR — Indian Rupee</option><option value="USD">USD — US Dollar</option><option value="AED">AED — UAE Dirham</option></select></label><label><span>Default tax rate %</span><input type="number" min="0" step="0.01" value={draft.defaultTaxRate} onChange={e=>setDraft({...draft,defaultTaxRate:Number(e.target.value)})}/></label><label><span>Financial year starts</span><input type="date" value={draft.financialYearStart} onChange={e=>setDraft({...draft,financialYearStart:e.target.value})}/></label><label><span>Invoice prefix</span><input value={draft.invoicePrefix} onChange={e=>setDraft({...draft,invoicePrefix:e.target.value.toUpperCase()})}/></label><label className="span-2"><span>Registered address</span><textarea rows={4} value={draft.address} onChange={e=>setDraft({...draft,address:e.target.value})}/></label><label className="toggle-label span-2"><input type="checkbox" checked={draft.lowStockAlerts} onChange={e=>setDraft({...draft,lowStockAlerts:e.target.checked})}/><span><strong>Low-stock alerts</strong><small>Show warnings when available quantity reaches the material reorder level.</small></span></label><label className="toggle-label span-2"><input type="checkbox" checked={draft.strictStockControl} onChange={e=>setDraft({...draft,strictStockControl:e.target.checked})}/><span><strong>Strict stock control</strong><small>Prevent material issues and auto-posting client invoices from creating negative stock.</small></span></label></div><div className="form-actions"><span className={saved?'save-message visible':'save-message'}>Settings saved</span><button className="button primary"><Save size={17}/> Save settings</button></div></form></article>
  <aside className="settings-side"><article className="panel setup-card"><div className={`setup-icon ${isSupabaseConfigured?'success':''}`}><Database size={24}/></div><h3>Database mode</h3><p>{isSupabaseConfigured?'Supabase environment variables are configured.':'The app is currently running in local browser storage mode.'}</p><span className={`status-pill ${isSupabaseConfigured?'success':'warning'}`}>{isSupabaseConfigured?'Supabase configured':'Local demo mode'}</span><hr/><p className="small-copy">Use the included SQL migration and Supabase setup guide to enable authentication, multi-user roles and cloud data.</p></article><article className="panel setup-card"><div className="setup-icon"><ShieldCheck size={24}/></div><h3>Recommended roles</h3><div className="role-list"><span>Owner</span><span>Admin</span><span>Accountant</span><span>Storekeeper</span><span>Site Engineer</span><span>Viewer</span></div></article><article className="panel setup-card danger-zone"><div className="setup-icon danger"><RotateCcw size={24}/></div><h3>Reset demo data</h3><p>Restore the original suppliers, sites, materials and transactions.</p><button className="button danger-button" onClick={()=>confirm('Reset all local data to the demo dataset?')&&resetDemo()}><RotateCcw size={16}/> Reset demo data</button></article></aside></section>
  </div>;
}
