import { Download, Eye, Plus, Trash2 } from 'lucide-react';
import { useMemo, useState, type FormEvent } from 'react';
import { Modal } from '../components/Modal';
import { PageHeader } from '../components/PageHeader';
import { SearchBar } from '../components/SearchBar';
import { TransactionItemsEditor } from '../components/TransactionItemsEditor';
import { currency, documentNo, downloadCsv, inventoryRows, itemsSubtotal, today, uid } from '../lib/helpers';
import { useApp } from '../store/AppContext';
import type { Supply } from '../types';

export function Supplies(){
  const {data,addSupply,deleteSupply}=useApp(); const stock=inventoryRows(data); const first=data.materials[0];
  const empty=():Supply=>({id:uid('iss'),issueNo:documentNo('ISS',data.supplies.length),date:today(),siteId:data.sites[0]?.id??'',requestedBy:'',approvedBy:'',vehicleNo:'',driverName:'',items:[{id:uid('si'),materialId:first?.id??'',quantity:1,rate:first?.standardRate??0,taxRate:first?.taxRate??0}],notes:'',createdAt:new Date().toISOString()});
  const [query,setQuery]=useState('');const[open,setOpen]=useState(false);const[view,setView]=useState<Supply|null>(null);const[draft,setDraft]=useState<Supply>(empty());const[error,setError]=useState('');
  const filtered=useMemo(()=>data.supplies.filter(s=>`${s.issueNo} ${s.vehicleNo} ${s.requestedBy} ${data.sites.find(x=>x.id===s.siteId)?.name}`.toLowerCase().includes(query.toLowerCase())),[data.supplies,data.sites,query]);
  const submit=(e:FormEvent)=>{e.preventDefault();const invalid=draft.items.find(i=>i.quantity>(stock.find(x=>x.id===i.materialId)?.availableQty??0));if(invalid){const m=data.materials.find(x=>x.id===invalid.materialId);setError(`Insufficient stock for ${m?.name}. Available: ${stock.find(x=>x.id===invalid.materialId)?.availableQty??0} ${m?.unit}.`);return;}addSupply(draft);setOpen(false);setError('');};
  return <div className="page-stack"><PageHeader eyebrow="Site dispatch" title="Material supplied" description="Issue materials to construction sites with approvals, vehicles, drivers and stock validation." actions={<><button className="button secondary" onClick={()=>downloadCsv('material-supplies.csv',filtered.map(s=>({Issue:s.issueNo,Date:s.date,Site:data.sites.find(x=>x.id===s.siteId)?.name,RequestedBy:s.requestedBy,Vehicle:s.vehicleNo,Value:itemsSubtotal(s.items)})))}><Download size={17}/> Export</button><button className="button primary" onClick={()=>{setDraft(empty());setError('');setOpen(true);}}><Plus size={17}/> Supply material</button></>} />
  <section className="panel table-panel"><div className="table-toolbar"><SearchBar value={query} onChange={setQuery} placeholder="Search issue, site, requester or vehicle..."/><div className="toolbar-summary"><strong>{filtered.length}</strong><span>issues</span></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Issue note</th><th>Date</th><th>Site</th><th>Request / approval</th><th>Dispatch</th><th>Items</th><th>Material value</th><th/></tr></thead><tbody>{filtered.map(s=><tr key={s.id}><td><strong>{s.issueNo}</strong><span>{s.notes||'Site material issue'}</span></td><td>{new Date(s.date).toLocaleDateString('en-IN')}</td><td><strong>{data.sites.find(x=>x.id===s.siteId)?.name||'—'}</strong><span>{data.sites.find(x=>x.id===s.siteId)?.location}</span></td><td><strong>{s.requestedBy||'—'}</strong><span>Approved: {s.approvedBy||'—'}</span></td><td><strong>{s.vehicleNo||'—'}</strong><span>{s.driverName||'No driver'}</span></td><td>{s.items.length}</td><td><strong>{currency(itemsSubtotal(s.items))}</strong></td><td><div className="row-actions"><button className="icon-button" onClick={()=>setView(s)}><Eye size={16}/></button><button className="icon-button danger" onClick={()=>confirm(`Delete ${s.issueNo}? Stock will be restored.`)&&deleteSupply(s.id)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div></section>
  <Modal open={open} title="Supply material to site" subtitle="Stock is checked before the site issue note is saved." onClose={()=>setOpen(false)} wide><form className="form-stack" onSubmit={submit}>{error&&<div className="alert danger-alert">{error}</div>}<div className="form-grid three"><label><span>Issue number *</span><input required value={draft.issueNo} onChange={e=>setDraft({...draft,issueNo:e.target.value})}/></label><label><span>Issue date *</span><input required type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label><span>Site *</span><select required value={draft.siteId} onChange={e=>setDraft({...draft,siteId:e.target.value})}><option value="">Select site</option>{data.sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label><span>Requested by</span><input value={draft.requestedBy} onChange={e=>setDraft({...draft,requestedBy:e.target.value})}/></label><label><span>Approved by</span><input value={draft.approvedBy} onChange={e=>setDraft({...draft,approvedBy:e.target.value})}/></label><label><span>Vehicle no.</span><input value={draft.vehicleNo} onChange={e=>setDraft({...draft,vehicleNo:e.target.value.toUpperCase()})}/></label><label><span>Driver name</span><input value={draft.driverName} onChange={e=>setDraft({...draft,driverName:e.target.value})}/></label></div><TransactionItemsEditor materials={data.materials} items={draft.items} onChange={items=>setDraft({...draft,items})}/><div className="stock-hint-grid">{draft.items.map(i=>{const m=stock.find(s=>s.id===i.materialId);return <span key={i.id}>{m?.name}: <strong>{m?.availableQty} {m?.unit} available</strong></span>})}</div><label><span>Notes / purpose</span><textarea rows={3} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><div className="form-actions"><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button primary">Save issue & deduct stock</button></div></form></Modal>
  <Modal open={Boolean(view)} title={view?.issueNo??'Issue'} subtitle="Site material issue details" onClose={()=>setView(null)} wide>{view&&<div className="document-view"><div className="document-meta"><div><span>Site</span><strong>{data.sites.find(s=>s.id===view.siteId)?.name}</strong></div><div><span>Date</span><strong>{new Date(view.date).toLocaleDateString('en-IN')}</strong></div><div><span>Requested</span><strong>{view.requestedBy||'—'}</strong></div><div><span>Approved</span><strong>{view.approvedBy||'—'}</strong></div></div><table className="items-table"><thead><tr><th>Material</th><th>Qty</th><th>Rate</th><th>Value</th></tr></thead><tbody>{view.items.map(i=><tr key={i.id}><td>{data.materials.find(m=>m.id===i.materialId)?.name}</td><td>{i.quantity} {data.materials.find(m=>m.id===i.materialId)?.unit}</td><td>{currency(i.rate)}</td><td>{currency(i.quantity*i.rate)}</td></tr>)}</tbody></table><div className="document-total"><strong>Material value {currency(itemsSubtotal(view.items))}</strong></div></div>}</Modal>
  </div>;
}
